services:
  - type: web
    name: laravelcapitales
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: tu_host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: tu_bd
      - key: DB_USERNAME
        value: tu_usuario
      - key: DB_PASSWORD
        value: tu_password
